name: build

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!trunk'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker build .

  cargo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker build .
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1.0.3
      with:
        command: publish
        args: --dry-run
